import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main>
        <div className="grid h-screen place-items-center">
          <div className="card-bg rounded-2xl text-white w-1/3">
            <div className="m-4">
              <Image
                className="rounded-2xl w-full"
                src="/images/image-equilibrium.jpg"
                width={300}
                height={300}
                alt="Ethereum Icon"
              />
            </div>
            <div className="m-4">
              <h4 className="font-bold">Equilibrium #3429</h4>
              <p className="break-words">Our Equilibrium collection promotes balance and calm.</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
